--AERONAVES
CREATE TABLE AERONAVE (
    id_aeronave NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    modelo VARCHAR2(255),
    ano_fabri NUMBER,
    fabricante VARCHAR2(255)
);

--CIDADE
CREATE TABLE CIDADE (
    id_cidade number GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome varchar2(255)
);

--AEROPORTO
CREATE TABLE AEROPORTO (
    id_aeroporto number GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255),
    cidade_id number,
    CONSTRAINT fk_aeroporto_cidade FOREIGN KEY (cidade_id) REFERENCES cidade(id_cidade)
);

--TRECHO
create table trecho (
    id_trecho number generated by default as identity primary key,
    tipo integer,
    cidade_origem number,
    cidade_destino number,
    CONSTRAINT fk_cidadeO_cidade FOREIGN KEY (cidade_origem) REFERENCES cidade(id_cidade),
    CONSTRAINT fk_cidadeD_cidade FOREIGN KEY (cidade_destino) REFERENCES cidade(id_cidade)
);

--VOO
CREATE TABLE VOO (
    id_voo NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hora_origem varchar2(255),
    data_origem DATE,
    hora_chegada varchar2(255),
    data_chegada DATE,
    id_techo NUMBER,
    FOREIGN KEY (id_techo) REFERENCES TRECHO (id_trecho)
);

--ASSENTO
CREATE TABLE ASSENTO (
    id_voo NUMBER,
    id_aeronave NUMBER,
    linha number,
    coluna number,
    constraint fk_id_voo_voo FOREIGN KEY (id_voo) REFERENCES VOO (id_voo),
    constraint fk_id_aeronave_aeronave FOREIGN KEY (id_aeronave) REFERENCES AERONAVE (id_aeronave)
);


